package com.scroller.ledtext.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_dark_primary = Color(0xFF4CD9E3)
val md_theme_dark_onPrimary = Color(0xFF00363A)
val md_theme_dark_primaryContainer = Color(0xFF004F54)
val md_theme_dark_onPrimaryContainer = Color(0xFF73F5FF)
val md_theme_dark_secondary = Color(0xFFB1CBCE)
val md_theme_dark_onSecondary = Color(0xFF1B3436)
val md_theme_dark_secondaryContainer = Color(0xFF324B4D)
val md_theme_dark_onSecondaryContainer = Color(0xFFCCE8EA)
val md_theme_dark_tertiary = Color(0xFFB6C7EA)
val md_theme_dark_onTertiary = Color(0xFF20304C)
val md_theme_dark_tertiaryContainer = Color(0xFF374764)
val md_theme_dark_onTertiaryContainer = Color(0xFFD6E3FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1C)
val md_theme_dark_onBackground = Color(0xFFE0E3E3)
val md_theme_dark_surface = Color(0xFF191C1C)
val md_theme_dark_onSurface = Color(0xFFE0E3E3)
val md_theme_dark_surfaceVariant = Color(0xFF3F4849)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC8C9)
val md_theme_dark_outline = Color(0xFF899393)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1C)
val md_theme_dark_inverseSurface = Color(0xFFE0E3E3)
val md_theme_dark_inversePrimary = Color(0xFF00696F)
val md_theme_dark_surfaceTint = Color(0xFF4CD9E3)
val md_theme_dark_outlineVariant = Color(0xFF3F4849)
val md_theme_dark_scrim = Color(0xFF000000)